!ArenaConfig
arenas:
  0: !Arena
    t: 100
    rand_all_colors: true
    blackouts: [10,20,30,40,50]
    items:
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
  1: !Arena
    t: 100
    rand_all_colors: true
    items:
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
  2: !Arena
    t: 100
    rand_all_colors: true
    items:
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
  3: !Arena
    t: 100
    rand_all_colors: true
    blackouts: [2,4,6,8,10,12,14,16,18,20]
    items:
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []