!ArenaConfig
arenas:
  0: !Arena
    t: 0
    rand_all_colors: true
    rand_all_sizes: true
    items:
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: BadGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []