!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
