!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    items:
    - !Item
      name: Wall
    - !Item
      name: CylinderTunnel
    - !Item
      name: GoodGoal
  1: !Arena
    t: 1000
    items:
    - !Item
      name: WallTransparent
    - !Item
      name: GoodGoal
  2: !Arena
    t: 1000
    items:
      - !Item
        name: Cardbox1
      - !Item
        name: BadGoal
      - !Item
        name: GoodGoal
  3: !Arena
    t: 1000
    items:
      - !Item
        name: DeathZone
      - !Item
        name: GoodGoal